<?php use MF\Controller\Action; ?>
<div class="container">
    <div class="row">

        <div class="col-md-12 mt-4">
            <div class="d-flex justify-content-center">
                   <input type="search" name="pesquisa" id="pesquisa" onkeyup="pesquisar('/pesquisar')">
            </div>
        </div>        
        <div class="col-md-12 mt-3">
        <table class="table table-dark" id="tabela">
            <thead>
                <tr>
                  <th scope="col">ID</th>
                  <th scope="col">Descricão</th>
                  <th scope="col">Valor</th>                  
                </tr>
            </thead>
            <tbody id="t_body">
            <?php 
                $produtos = $this->view->produtos;
                foreach($produtos as $produto) { ?>
                  <tr>
                  <th scope="row"><?= $produto['id']?></th>
                  <td><?= $produto['descricao']?></td>
                  <td><?= $produto['valor']?></td>                  
                </tr> 

              <?php } ?>
                    
                               
            </tbody>
                </table>

        </div>  
    </div>
</div>